### ISSUE TITLE
Link - Page Not Found

### ISSUE THREAD

**Issue by felipecastrosales** [joaopealves/ex_cnab#10]
Hi @joaopealves, interesting project. 

I noticed that the link in that section below is `Not Found`. 

<img src="https://user-images.githubusercontent.com/59374587/231323752-0f6a3109-4227-4044-a863-e732bc828883.png" width="40%">

Having this result: 

![image](https://user-images.githubusercontent.com/59374587/231323483-eb9e5cdb-1e11-4ecc-ab0b-feade1d96b1c.png)

I believe it's just updating it to what is suggested :D

**Comment by joaopealves** [comment]
Hey @felipecastrosales, how are you doing?

Thanks for the reply, the error has already been fixed.

The correct url is this hexdocs.pm/ex_cnab/

Best regards, João
